### ISSUE TITLE
[style] tax_agg should return aggregated data

### ISSUE THREAD

**Issue by EDiLD** [ropensci/taxize#177]
Store other information as attributes.

**Comment by sckott** [comment]
@EDiLD is this fixed now?

**Comment by EDiLD** [comment]
No, not fixed. 
Keep this open - I am currently full with work, but next month maybe....

**Comment by sckott** [comment]
okay, thx

**Comment by sckott** [comment]
@EDiLD can we close this or is it already fixed, been almost 2 yrs now
