### ISSUE TITLE
iucn_summary API key

### ISSUE THREAD

**Issue by PrincessPi314** [ropensci/taxize#735]
When I use the iucn_summary function with my IUCN API key I get the error:

> iucn_summary("Lutra lutra", key= "XXX")

Retrieving data for taxon 'Lutra lutra'

Error: need an API key for Red List data

The strange thing is the key works when I use the functions from the rredlist package or in the function iucn_id() .....

<details> <summary><strong>Session Info</strong></summary>

```r

```
</details>

**Comment by sckott** [comment]
Can you please share your `sessionInfo()` (or `devtools::session_info()`)

**Comment by PrincessPi314** [comment]
Session info ---------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.0 (2017-04-21)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.0.143)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Copenhagen           
 date     2019-02-13  

Packages ------------------------------------------------------------------------------------------
 taxize     * 0.9.3    2018-03-20 CRAN (R 3.4.4)

**Comment by sckott** [comment]
@PrincessPi314 would you be willing to update? At least to the current CRAN version `v0.9.5` 

It's fixed in the current version on CRAn

**Comment by PrincessPi314** [comment]
I updated taxize, but the problem remains the same:
> iucn_summary("Lutra lutra", key="xxx")
Retrieving data for taxon 'Lutra lutra'
Error: need an API key for Red List data

> iucn_id("Lutra lutra", key="xxx")
[1] 12419

Session info: 

Session info -------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.0 (2017-04-21)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.0.143)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Copenhagen           
 date     2019-02-14 

taxize     * 0.9.5   2019-01-30 CRAN (R 3.4.4)

**Comment by sckott** [comment]
Did you reload R after installing the new version?

**Comment by PrincessPi314** [comment]
Yes, I did but its still not working. I get a warning when loading the taxize library: 
Warning message:
package ‘taxize’ was built under R version 3.4.4 
i guess i should update R...

**Comment by sckott** [comment]
It wouldn't hurt to get the latest version of R. Let me know what happens

**Comment by PrincessPi314** [comment]
Just ran the function on my colleagues computer who has the latest version of R, the latest version of taxize and is using a different IUCN API key and she has the same problem....
Not sure what else can be done...

Her session info:

─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.5.2 (2018-12-20)
 os       OS X El Capitan 10.11.6     
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Copenhagen           
 date     2019-02-18                  

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 taxize      * 0.9.5   2019-01-30 [1] CRAN (R 3.5.2)

**Comment by sckott** [comment]
@PrincessPi314 can you reinstall `remotes::install_github("ropensci/taxize")` and try again pleas, should be fixed now

**Comment by PrincessPi314** [comment]
It works! Thank you so much!!!!!!

**Comment by sckott** [comment]
great, glad it works now
