### ISSUE TITLE
curl_fetch_memory failed to match connection hostname

### ISSUE THREAD

**Issue by p-schaefer** [ropensci/taxize#771]
I'm having an issue with `gnr_resolve` for instance:

`gnr_resolve("Simuliidae")`

> Error in curl::curl_fetch_memory(x$url$url, handle = x$url$handle) : 
  schannel: CertGetNameString() failed to match connection hostname (resolver.globalnames.org) against server certificate names

I'm using R 3.6.1 and taxize 0.9.8.9134

**Comment by sckott** [comment]
thanks for the issue

is it a persistent problem? if you do the request again does it still happen?  That error definitely seems like a problem on their end, and probably is temporary

**Comment by p-schaefer** [comment]
So far yes. I agree it sounds like a problem with GNR, but am wondering if their API may have changed.

**Comment by sckott** [comment]
It's not happening for me though, so it may be a factor of the network you're on. Do you know if you're behind a proxy or if the place you're at blocks certain ports. If you can get on a VPN I'd try the request on that to see if you get a different result

**Comment by jeroen** [comment]
This was a bug in curl. If you reinstall curl it should be fixed :)

**Comment by p-schaefer** [comment]
That didn't fix it unfortunately. I tried reinstalling curl and crul. It also works for me at home, so its likely a problem with the network I'm on at work. What ports need to be open?

`sessionInfo()`
> R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] taxize_0.9.8.9134

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2        compiler_3.6.1    plyr_1.8.4        iterators_1.0.12  tools_3.6.1       jsonlite_1.6     
 [7] nlme_3.1-140      lattice_0.20-38   Matrix_1.2-17     foreach_1.4.7     cli_1.1.0         rstudioapi_0.10  
[13] crul_0.8.0        curl_4.0          parallel_3.6.1    mvtnorm_1.0-11    coda_0.19-3       stringr_1.4.0    
[19] xml2_1.2.1        triebeard_0.3.0   grid_3.6.1        reshape_0.8.8     httpcode_0.2.0    data.table_1.12.2
[25] R6_2.4.0          survival_2.44-1.1 multcomp_1.4-10   TH.data_1.0-10    reshape2_1.4.3    magrittr_1.5     
[31] urltools_1.7.3    codetools_0.2-16  emmeans_1.3.5.1   MASS_7.3-51.4     splines_3.6.1     assertthat_0.2.1 
[37] bold_0.9.0        ape_5.3           xtable_1.8-4      sandwich_2.5-1    estimability_1.3  stringi_1.4.3    
[43] crayon_1.3.4      zoo_1.8-6

**Comment by jeroen** [comment]
Hmmm you are not using httr, right?

**Comment by p-schaefer** [comment]
No, cf `sessionInfo()` above.

**Comment by jeroen** [comment]
Ah I see the problem now, `crul` has the same bug as httr. @sckott you need to remove the default `cainfo` option in `crul` as done here: https://github.com/r-lib/httr/pull/603

**Comment by sckott** [comment]
@p-schaefer install dev `crul` `remotes::install_github("ropensci/crul")` and reload and try again - should be pushing crul to CRAN today

**Comment by p-schaefer** [comment]
Works now. Thanks!
